### ISSUE TITLE
Select CRF value

### ISSUE THREAD

**Issue by quantumgolem** [aikinai/Scripts#1]
How do you select a CRF value other than 26 when encoding images to heic? (Other than changing the script myself) I'm just wondering if there's a way to set it as a command line argument or something

**Comment by aikinai** [comment]
You can just set it as an environment variable beforehand and it will override the default 26 hard-coded into the script. Like this:

`CRF=18 ./encode-heic.sh image.tiff`

You can change the [preset](https://x265.readthedocs.io/en/stable/presets.html) using the same method. It defaults to `slower`, which I think is pretty good, but maybe it's worth testing `veryslow`? I believe `placebo` is, as the name indicates, not worth it.
